version: '3'

services:
  server:
    build: .
    command: yarn run_dev
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/postgresdb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/prisma

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"       

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge